### ISSUE TITLE
'Debug -> Dump Style Sheets' is failed for https://news.google.com/home

### ISSUE THREAD

**Issue by SverdlovBohdan** [LadybirdBrowser/ladybird#4671]
### Summary

'Debug -> Dump Style Sheets' is failed for https://news.google.com/home

### Operating system

macOS

### Steps to reproduce

1. Start Ladybird
2. Open the https://news.google.com/home
3. Call the Debug -> Dump Style Sheets

Found in commit 6941b6389037193977d147c8d8a26f6233895f9f

### Expected behavior

Style Sheets are dumped successfully.

### Actual behavior

The Style Sheets are not dumped fully

```
3633.787 WebContent(15305): === In document: ===
3633.787 WebContent(15305): CSSStyleSheet{0x00000001692e4520}: 6 rule(s)
CSSFontFaceRule:
  VALID: true
  font-family: Google Sans Text
  weight: 400
  slope: 0
  width: 5
  sources:
    url=url("https://fonts.gstatic.com/s/googlesanstext/v23/5aUo9-KzpRiLCAt4Unrc-xIKmCU5qE9GiU9D.ttf"), format=truetype
  unicode-ranges:
    U+0-10FFFF
  display: auto
CSSFontFaceRule:
  VALID: true
  font-family: Google Sans Text
  weight: 500
  slope: 0
  width: 5
  sources:
    url=url("https://fonts.gstatic.com/s/googlesanstext/v23/5aUr9-KzpRiLCAt4Unrc-xIKmCU5qE9OemxTtDO6.ttf"), format=truetype
  unicode-ranges:
    U+0-10FFFF
  display: auto
CSSFontFaceRule:
  VALID: true
  font-family: Google Sans Text
  weight: 700
  slope: 0
  width: 5
  sources:
    url=url("https://fonts.gstatic.com/s/googlesanstext/v23/5aUr9-KzpRiLCAt4Unrc-xIKmCU5qE9OMmpTtDO6.ttf"), format=truetype
  unicode-ranges:
    U+0-10FFFF
  display: auto
CSSFontFaceRule:
  VALID: true
  font-family: Google Sans Text
  weight: 400
  slope: 0
  width: 5
  sources:
    url=url("https://fonts.gstatic.com/s/googlesanstext/v23/5aUu9-KzpRiLCAt4Unrc-xIKmCU5qEp2jg.ttf"), format=truetype
  unicode-ranges:
    U+0-10FFFF
  display: auto
CSSFontFaceRule:
  VALID: true
  font-family: Google Sans Text
  weight: 500
  slope: 0
  width: 5
  sources:
    url=url("https://fonts.gstatic.com/s/googlesanstext/v23/5aUp9-KzpRiLCAt4Unrc-xIKmCU5oLlVnmhjsw.ttf"), format=truetype
  unicode-ranges:
    U+0-10FFFF
  display: auto
CSSFontFaceRule:
  VALID: true
  font-family: Google Sans Text
  weight: 700
  slope: 0
  width: 5
  sources:
    url=url("https://fonts.gstatic.com/s/googlesanstext/v23/5aUp9-KzpRiLCAt4Unrc-xIKmCU5oPFTnmhjsw.ttf"), format=truetype
  unicode-ranges:
    U+0-10FFFF
  display: auto

VERIFICATION FAILED: false at ladybird/Build/release/Lagom/Libraries/LibWeb/CSS/PseudoElement.cpp:164
0   liblagom-ak.0.0.0.dylib             0x0000000103105658 dump_backtrace + 72
1   liblagom-ak.0.0.0.dylib             0x000000010313e66c ak_trap + 12
2   liblagom-ak.0.0.0.dylib             0x000000010313e720 ak_assertion_failed + 0
3   liblagom-web.0.0.0.dylib            0x00000001054b7dd4 Web::CSS::pseudo_element_name(Web::CSS::PseudoElement) + 520
4   liblagom-web.0.0.0.dylib            0x0000000104ff8cc0 Web::dump_selector(AK::StringBuilder&, Web::CSS::Selector const&, int) + 1260
5   liblagom-web.0.0.0.dylib            0x0000000104ffaca4 Web::dump_style_rule(AK::StringBuilder&, Web::CSS::CSSStyleRule const&, int) + 100
6   liblagom-web.0.0.0.dylib            0x0000000104ff96b4 Web::dump_rule(AK::StringBuilder&, Web::CSS::CSSRule const&, int) + 488
7   liblagom-web.0.0.0.dylib            0x0000000104ffbc2c Web::dump_sheet(AK::StringBuilder&, Web::CSS::StyleSheet const&) + 160
8   liblagom-web.0.0.0.dylib            0x0000000104ffbb04 Web::dump_sheet(Web::CSS::StyleSheet const&) + 56
9   WebContent                          0x00000001026d17ec WebContent::ConnectionFromClient::debug_request(unsigned long long, AK::ByteString, AK::ByteString) + 692
10  WebContent                          0x00000001026dc9ec WebContentServerStub::handle(AK::NonnullOwnPtr<IPC::Message>) + 1228
11  liblagom-ipc.0.0.0.dylib            0x0000000102b206d4 IPC::ConnectionBase::handle_messages() + 240
12  liblagom-core.0.0.0.dylib           0x0000000102f381f0 AK::Function<void ()>::CallableWrapper<Core::EventReceiver::deferred_invoke(AK::Function<void ()>)::$_0>::call() + 92
13  liblagom-core.0.0.0.dylib           0x0000000102f455dc Core::ThreadEventQueue::process() + 512
14  liblagom-core.0.0.0.dylib           0x0000000102f4b8f0 Core::EventLoopImplementationUnix::exec() + 44
15  liblagom-core.0.0.0.dylib           0x0000000102f35894 Core::EventLoop::exec() + 72
16  WebContent                          0x00000001026cc4e8 serenity_main(Main::Arguments) + 3952
17  WebContent                          0x00000001027869c4 main + 196
18  dyld                                0x00000001957f2b98 start + 6076
```

### URL for a reduced test case

https://news.google.com/home

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
VERIFICATION FAILED: false at ladybird/Build/release/Lagom/Libraries/LibWeb/CSS/PseudoElement.cpp:164
0   liblagom-ak.0.0.0.dylib             0x0000000103105658 dump_backtrace + 72
1   liblagom-ak.0.0.0.dylib             0x000000010313e66c ak_trap + 12
2   liblagom-ak.0.0.0.dylib             0x000000010313e720 ak_assertion_failed + 0
3   liblagom-web.0.0.0.dylib            0x00000001054b7dd4 Web::CSS::pseudo_element_name(Web::CSS::PseudoElement) + 520
4   liblagom-web.0.0.0.dylib            0x0000000104ff8cc0 Web::dump_selector(AK::StringBuilder&, Web::CSS::Selector const&, int) + 1260
5   liblagom-web.0.0.0.dylib            0x0000000104ffaca4 Web::dump_style_rule(AK::StringBuilder&, Web::CSS::CSSStyleRule const&, int) + 100
6   liblagom-web.0.0.0.dylib            0x0000000104ff96b4 Web::dump_rule(AK::StringBuilder&, Web::CSS::CSSRule const&, int) + 488
7   liblagom-web.0.0.0.dylib            0x0000000104ffbc2c Web::dump_sheet(AK::StringBuilder&, Web::CSS::StyleSheet const&) + 160
8   liblagom-web.0.0.0.dylib            0x0000000104ffbb04 Web::dump_sheet(Web::CSS::StyleSheet const&) + 56
9   WebContent                          0x00000001026d17ec WebContent::ConnectionFromClient::debug_request(unsigned long long, AK::ByteString, AK::ByteString) + 692
10  WebContent                          0x00000001026dc9ec WebContentServerStub::handle(AK::NonnullOwnPtr<IPC::Message>) + 1228
11  liblagom-ipc.0.0.0.dylib            0x0000000102b206d4 IPC::ConnectionBase::handle_messages() + 240
12  liblagom-core.0.0.0.dylib           0x0000000102f381f0 AK::Function<void ()>::CallableWrapper<Core::EventReceiver::deferred_invoke(AK::Function<void ()>)::$_0>::call() + 92
13  liblagom-core.0.0.0.dylib           0x0000000102f455dc Core::ThreadEventQueue::process() + 512
14  liblagom-core.0.0.0.dylib           0x0000000102f4b8f0 Core::EventLoopImplementationUnix::exec() + 44
15  liblagom-core.0.0.0.dylib           0x0000000102f35894 Core::EventLoop::exec() + 72
16  WebContent                          0x00000001026cc4e8 serenity_main(Main::Arguments) + 3952
17  WebContent                          0x00000001027869c4 main + 196
18  dyld                                0x00000001957f2b98 start + 6076
```

### Build flags or config settings

CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ ./Meta/ladybird.sh run

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by AtkinsSJ** [comment]
Hi! This should actually be fixed by the couple of commits that followed https://github.com/LadybirdBrowser/ladybird/commit/6941b6389037193977d147c8d8a26f6233895f9f - bad timing I guess!

**Comment by SverdlovBohdan** [comment]
Hi. Rechecked on 123abe0e79354d4cfc005adc973688f6e378365a 

Issue is not fixed, but the output is different.

```
CSSStyleRule:
  CSS::Selector:
    {None} Class:dm7YTc
    {Descendant} Class:Jkpske
    {Descendant} Class:c0uh4c, PseudoClassSelector: pseudo_class=disabled
  Declarations (1):
    color: 'rgba(227, 227, 227, 0.38)'
  Child rules (0):
CSSStyleRule:
  CSS::Selector:
    {None} Class:dm7YTc
    {Descendant} Class:Jkpske
    {Descendant} Class:c0uh4c, PseudoClassSelector: pseudo_class=disabled
  Declarations (1):
    background-color: 'rgba(227, 227, 227, 0.12)'
  Child rules (0):
CSSStyleRule:
  CSS::Selector:
    {None} Class:gEvipf
  Declarations (6):
    display: 'flex'
    flex-direction: 'column'
    flex-direction: 'column'
    align-items: 'end'
    align-items: 'flex-end'
    align-items: 'flex-end'
  Child rules (0):
CSSStyleRule:
  CSS::Selector:
    {None} TagName:NamespaceType=Default, Namespace='', Name='sentinel'
  Declarations (0):
  Child rules (0):

5250.109 WebContent(25814): CSSStyleSheet{0x000000014628c8c8}: 2 rule(s)
CSSStyleRule:
  CSS::Selector:
    {None} Id:i11
  Declarations (1):
    color: 'rgb(24, 103, 220)'
  Child rules (0):
CSSStyleRule:
  CSS::Selector:
    {None} Class:dm7YTc
    {Descendant} Id:i11
  Declarations (1):
    color: 'rgb(139, 184, 248)'
  Child rules (0):

5250.109 WebContent(25814): CSSStyleSheet{0x000000014628deb8}: 2 rule(s)
CSSStyleRule:
  CSS::Selector:
    {None} Id:i30
  Declarations (1):
    color: 'rgb(89, 47, 208)'
  Child rules (0):
CSSStyleRule:
  CSS::Selector:
    {None} Class:dm7YTc
    {Descendant} Id:i30
  Declarations (1):
    color: 'rgb(165, 150, 207)'
  Child rules (0):

5250.109 WebContent(25814): CSSStyleSheet{0x000000014628e260}: 2 rule(s)
CSSStyleRule:
  CSS::Selector:
    {None} Id:i31
  Declarations (1):
    background-color: 'rgb(89, 47, 208)'
  Child rules (0):
CSSStyleRule:
  CSS::Selector:
    {None} Class:dm7YTc
    {Descendant} Id:i31
  Declarations (1):
    background-color: 'rgb(165, 150, 207)'
  Child rules (0):

5250.109 WebContent(25814): === In shadow root input.yNVtPc.ZAGvjd.Ny5lGc: ===
5250.109 WebContent(25814): === In shadow root input.Ax4B8.ZAGvjd: ===
5250.318 Ladybird(25803): WebContent process crashed! Last page loaded: https://news.google.com/home?hl=en-US&gl=US&ceid=US:en
5250.318 Ladybird(25803): Consider raising an issue at https://github.com/LadybirdBrowser/ladybird/issues/new/choose
5250.322 WebContent(25852): FIXME: Handle null navigation_request in navigation response Content Security Policy check.
```

**Comment by AtkinsSJ** [comment]
Thanks! So it's related to shadow roots by the look of it.

**Comment by R-Goc** [comment]
reproduces on other websites

**Comment by AtkinsSJ** [comment]
Hmm, I'm trying to debug this today and it's no longer crashing. I had a look back and it seems like f61df9d34cb fixed it. Before that, it crashes. With that commit, it doesn't. (And that commit touches shadow trees, so it makes sense.)

If there are other websites (or ideally a small test case) then do post that here and I'll reopen it.
