### ISSUE TITLE
Non functional (broken) href/links/buttons

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [LadybirdBrowser/ladybird#5372]
### Summary

After building and running Ladybird on macOS, none of the interactive buttons ("Alle producten", "Meer weten", or product links) on https://www.clickhere.nl/ respond to clicks.

### Operating system

macOS

### Steps to reproduce

1. Visit https://www.clickhere.nl
2. Attempt to click on any of the following:
- "Meer weten"
- "Alle producten"
- Any of the product buttons or links

### Expected behavior

Clicking any of these buttons or links should trigger navigation, as they do in mainstream browsers.

### Actual behavior

Nothing happens, you can see the redirect URL bottom left of your screen but it does not redirect you on click

### URL for a reduced test case

https://www.clickhere.nl/

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
171592.323 WebContent(33782): WindowGlobalMixin::document_getter()
171592.323 WebContent(33782): DocumentPrototype::get_element_by_id("fader")
171592.323 WebContent(33782): EventPrototype::current_target_getter()
171592.323 WebContent(33782): EventTargetPrototype::add_event_listener("animationend", [object ECMAScriptFunctionObject])
171592.323 WebContent(33782): EventPrototype::prevent_default()
171592.323 WebContent(33782): ElementPrototype::class_list_getter()
171592.323 WebContent(33782): DOMTokenListPrototype::add("fade-in")
171592.324 WebContent(33782): EventPrototype::target_getter()
171592.324 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.324 WebContent(33782): NodePrototype::parent_node_getter()
171592.324 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.324 WebContent(33782): NodePrototype::parent_node_getter()
171592.324 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.324 WebContent(33782): NodePrototype::parent_node_getter()
171592.324 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): EventPrototype::target_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): EventPrototype::target_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): EventPrototype::target_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.325 WebContent(33782): NodePrototype::parent_node_getter()
171592.325 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): EventPrototype::target_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): EventPrototype::target_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("a[data-confirm], a[data-method], a[data-remote]:not([disabled]), a[data-disable-with], a[data-disable]")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): EventPrototype::target_getter()
171592.326 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.326 WebContent(33782): NodePrototype::parent_node_getter()
171592.326 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): EventPrototype::target_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): EventPrototype::target_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): EventPrototype::target_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.327 WebContent(33782): NodePrototype::parent_node_getter()
171592.327 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): EventPrototype::target_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("button[data-remote]:not([form]), button[data-confirm]:not([form])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): EventPrototype::target_getter()
171592.328 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.328 WebContent(33782): NodePrototype::parent_node_getter()
171592.328 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): EventPrototype::target_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): EventPrototype::target_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.329 WebContent(33782): NodePrototype::parent_node_getter()
171592.329 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): EventPrototype::target_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.330 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.330 WebContent(33782): NodePrototype::parent_node_getter()
171592.331 WebContent(33782): ElementPrototype::matches("form:not([data-turbo=true]) input[type=submit], form:not([data-turbo=true]) input[type=image], form:not([data-turbo=true]) button[type=submit], form:not([data-turbo=true]) button:not([type]), input[type=submit][form], input[type=image][form], button[type=submit][form], button[form]:not([type])")
171592.331 WebContent(33782): NodePrototype::parent_node_getter()
```

### Screenshots or screen recordings

<img width="559" height="185" alt="Image" src="https://github.com/user-attachments/assets/ba6f6c57-14f4-4f37-b668-db7d4d6876a7" />

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by AtkinsSJ** [comment]
The on click event handler for these looks like this:

```js
function(event) {
  var fader = document.getElementById('fader'),
    anchor = event.currentTarget;
  var listener = function() {
    window.location = anchor.href;
    fader.removeEventListener('animationend', listener);
  };
  fader.addEventListener('animationend', listener);
  event.preventDefault();
  fader.classList.add('fade-in');
}
```

So it disables the usual click response, sets a callback to navigate when an `animationend` event happens on the `fader` element, then starts a transition on that element.

I don't know if we produce `animationend` events for transitions, so that's probably a good place to start looking.

**Comment by vpzomtrrfrt** [comment]
As of today on 670cbccb, clicking a link on this site causes the screen to change to a solid blue, but hovering over portions of it still shows link targets

**Comment by vpzomtrrfrt** [comment]
It looks like they're using animations, not transitions

**Comment by vpzomtrrfrt** [comment]
The problem appears to be related to overriding animation-name on an element that already had an animation.
```html
<!DOCTYPE html>
<html>
	<head>
		<style>
			#box {
				width: 100px;
				height: 100px;
				animation-duration: 2s;
			}

			#box.foo {
				animation-name: foo;
				background-color: black;
			}

			#box.bar {
				animation-name: bar;
				background-color: yellow;
			}

			@keyframes foo {
				from {
					background-color: lime;
				}
				to {
					background-color: black;
				}
			}

			@keyframes bar {
				from {
					background-color: blue;
				}
				to {
					background-color: yellow;
				}
			}
		</style>
	</head>
	<body>
		<div id="box" class="foo"></div>
		<script>
			const box = document.getElementById("box");
			box.addEventListener("click", () => {
				box.classList.add("bar");
			});
		</script>
	</body>
</html>
```

This snippet displays a square that animates from lime to black, and when clicked, it should switch to animating from blue to yellow. This works fine in Firefox, but Ladybird instead plays out the whole first animation before instantly switching to yellow.

**Comment by tcl3** [comment]
Fixed by 84762021b81

**Comment by sanderDijkxhoorn** [comment]
@tcl3 most buttons work now but the logo in the menu which goes to "/" is still broken.

**Comment by tcl3** [comment]
@sanderDijkxhoorn I can't reproduce this, is it still not working for you? Can you give more information about the steps you took and what happens when you click the logo.

**Comment by sanderDijkxhoorn** [comment]
@tcl3 since my last comment it seems to be resolved, I can't reproduce it anymore either. Let's close the ticket for now. Thanks to everyone involved that looked into the issue.
